// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyrvfcgfouovivtkhkcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cnZmY2dmb3Vvdml2dGtoa2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzkyMjEsImV4cCI6MjA3MjY1NTIyMX0.3LkxaqHmgbOD-bKYWyue6fX17_cPTyZNGVuFtsMbEDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});